### ISSUE TITLE
[Bugs] 复读图片出现报错

### ISSUE THREAD

**Issue by KafCoppelia** [ninthseason/nonebot-plugin-repeater#2]
复读图库的图片或者已添加进表情中的图片，复读时报错：
01-04 10:21:18 [ERROR] nonebot | Running matcher <Matcher from repeater, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "/root/anaconda3/envs/nonebot_v2/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
  File "/root/NONEBOT/AQUABOT/src/plugins/repeater/__init__.py", line 48, in repeater
    await bot.send(event, data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 471, in send
    return await self.send_msg(**params)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 416, in call_api
    return await super().call_api(api, **data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 172, in call_api
    raise exception
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 155, in call_api
    result = await self._call_api(api, **data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 363, in _call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 192, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 264}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

GO-CQHTTP端报错：
[2022-01-04 10:21:18] [WARNING]: 转换CQ码 ({"type": "image", "data": {"file": "ype=1", "type": null, "cache": "true", "proxy": "true", "timeout": null}}) 到MiraiGo Element时出现错误: invalid image 将忽略本段CQ码. 
[2022-01-04 10:21:18] [WARNING]: 群消息发送失败: 消息为空.

**Comment by ninthseason** [comment]
遗憾的是，我并没有复现出这个Bug，你是否有空克隆最新的代码，将日志展示出来。

**Comment by KafCoppelia** [comment]
clone了最新代码，报错
01-04 11:52:15 [DEBUG] repeater | [CQ:image,file=845db5a01a264d3d935d1c2a631fd0b0.image,url=https://gchat.qpic.cn/gchatpic_new/740677208/2151831838-2999456822-845DB5A01A264D3D935D1C2A631FD0B0/0?term=3,subType=1]
01-04 11:52:15 [DEBUG] repeater | CQ:image
01-04 11:52:15 [DEBUG] repeater | [CQ:image,file=ype=1,cache=true,proxy=true]
01-04 11:52:15 [DEBUG] nonebot | CQHTTP | Calling API send_msg
01-04 11:52:15 [DEBUG] nonebot | Running CalledAPI hooks...
01-04 11:52:15 [DEBUG] nonebot | CQHTTP | Calling API get_login_info
01-04 11:52:15 [DEBUG] nonebot | Running CalledAPI hooks...
01-04 11:52:15 [DEBUG] nonebot | CQHTTP | Calling API get_group_info
01-04 11:52:15 [DEBUG] nonebot | Running CalledAPI hooks...
01-04 11:52:15 [INFO] nonebot | Matcher <Matcher from repeater, type=message, priority=10, temp=False> running complete
01-04 11:52:15 [ERROR] nonebot | Running matcher <Matcher from repeater, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
  File "/root/NONEBOT/AQUABOT/src/plugins/repeater/__init__.py", line 50, in repeater
    await bot.send(event, data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 471, in send
    return await self.send_msg(**params)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 416, in call_api
    return await super().call_api(api, **data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 172, in call_api
    raise exception
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 155, in call_api
    result = await self._call_api(api, **data)
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 363, in _call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 192, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 6}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

`type`那个“t”被截掉了吧？🤔

**Comment by ninthseason** [comment]
找了Bug了。

Amazing, 我所收到的图片消息，数据顺序与你的不同，导致截取数据出现问题。

> 
``` python
[CQ:image,file=f5185e339938c160e3feab20a38be780.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/2351859943/835091305-2943711516-F5185E339938C160E3FEAB20A38BE780/0?term=3]
```

我将很快修复该bug。

**Comment by ninthseason** [comment]
已修复

**Comment by KafCoppelia** [comment]
已验证
